name: Update Docker Hub Readme
on:
  push:
    branches:
      - master
    paths:
      - README.md
      - .github/workflows/dockerhub-readme.yml

  workflow_dispatch:
jobs:
  dockerHubDescription:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Docker Hub Description
      uses: peter-evans/dockerhub-description@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}
        repository: shirom/pihole-sync
