name: Push to DockerHub 

on:
  push:
    branches: [ master ]
    paths-ignore: [ README.md ]
  pull_request:
    branches: [ master ]
    paths-ignore: [ README.md ]

  workflow_dispatch:

# https://github.com/docker/build-push-action/blob/master/docs/advanced/multi-platform.md
jobs:
  build-push:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          platforms: linux/amd64,linux/arm64,linux/arm/v6,linux/arm/v7
          push: true
          tags: shirom/pihole-sync:latest
